In [2]:
import numpy as np

ndarray: Серце бібліотеки NumPy

ndarray — це багатовимірний однорідний масив (всі елементи одного типу).

Тип даних кожного елемента задається об'єктом dtype.

Ключові атрибути масиву:

| Атрибут     | Опис                                                             |
|-------------|------------------------------------------------------------------|
| `dtype`     | Тип елементів у масиві                                          |
| `ndim`      | Кількість вимірів (осей)                                        |
| `shape`     | Форма (розміри по кожній осі), наприклад `(3, 4)`               |
| `size`      | Загальна кількість елементів у масиві                           |
| `itemsize`  | Розмір одного елемента в байтах                                 |
| `data`      | Вказівник на блок пам’яті з фактичними елементами масиву       |



In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))       # <class 'numpy.ndarray'>
print(a.dtype)       # int32 (або int64)
print(a.ndim)        # 1
print(a.shape)       # (3,)
print(a.size)        # 3
print(a.itemsize)    # 4 або 8 (залежить від платформи)


<class 'numpy.ndarray'>
int64
1
(3,)
3
8


# Створення масиву

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([(1, 2), [3, 4], (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

## типи даних

| Data Type   | Description                                                                                           |
|:------------|:------------------------------------------------------------------------------------------------------|
| `bool_`     | Булевий тип (true або false), збережений у вигляді байта                                               |
| `int_`      | Знаковий тип цілого числа (як у C long та Python int; зазвичай int64 або int32 залежно від платформи) |
| `intc`      | Знаковий тип цілого числа, ідентичний до C int (зазвичай int32 або int64)                             |
| `intptr`    | Ціле число для індексування (як size_t у C; зазвичай int32 або int64)                                |
| `int8`      | Псевдонім знакового цілого типу з 8 бітами (−128 до 127)                                             |
| `int16`     | Псевдонім знакового цілого типу з 16 бітами (−32768 до 32767)                                        |
| `int32`     | Псевдонім знакового цілого типу з 32 бітами (−2147483648 до 2147483647)                              |
| `int64`     | Псевдонім знакового цілого типу з 64 бітами (−9223372036854775808 до 9223372036854775807)            |
| `uint8`     | Псевдонім беззнакового цілого типу з 8 бітами (0 до 255)                                             |
| `uint16`    | Псевдонім беззнакового цілого типу з 16 бітами (0 до 65535)                                          |
| `uint32`    | Псевдонім беззнакового цілого типу з 32 бітами (0 до 4294967295)                                     |
| `uint64`    | Псевдонім беззнакового цілого типу з 64 бітами (0 до 18446744073709551615)                          |
| `float_`    | Скорочений запис для float64                                                                          |
| `float16`   | Число з плаваючою комою напівточності: біт знаку, 5-бітний експонент, 10-бітова мантиса               |
| `float32`   | Число з плаваючою комою одиничної точності: біт знаку, 8-бітний експонент, 23-бітова мантиса           |
| `float64`   | Число з плаваючою комою подвійної точності: біт знаку, 11-бітний експонент, 52-бітова мантиса          |
| `complex_`  | Скорочений запис для complex128                                                                       |
| `complex64` | Комплексне число, представлене двома 32-бітними числами з плаваючою комою (дійсна та уявна частини)   |
| `complex128`| Комплексне число, представлене двома 64-бітними числами з плаваючою комою (дійсна та уявна частини)   |


In [8]:
b = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(b.dtype)  # float32


float32


## Створення масивів іншими способами

| Функція                         | Пояснення                                                                 |
|-------------------------------|---------------------------------------------------------------------------|
| `np.zeros(shape)`             | Створює масив заданої форми, заповнений нулями                            |
| `np.ones(shape)`              | Створює масив заданої форми, заповнений одиницями                         |
| `np.arange(stop)`             | Створює послідовність від 0 до `stop` (не включно)                         |
| `np.arange(start, stop)`      | Послідовність від `start` до `stop` (не включно)                          |
| `np.arange(start, stop, step)`| Послідовність з кроком `step`                                             |
| `np.linspace(start, stop, num)` | Повертає `num` значень між `start` і `stop` з рівним інтервалом          |
| `np.random.random(size)`      | Масив заданого розміру з випадковими числами від 0 до 1                   |
| `arr.reshape(shape)`          | Перетворює одномірний масив у масив заданої форми                         |


In [9]:
print(np.zeros((3, 3)))
print(np.ones((3, 3)) )


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.arange(0, 10)  )
print(np.arange(4, 10))
print(np.arange(0, 12, 3))
print(np.arange(0, 6, 0.6))
print(np.arange(0, 12).reshape(3, 4))


[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[0 3 6 9]
[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print(np.linspace(0, 10, 5))


[ 0.   2.5  5.   7.5 10. ]


In [12]:
print(np.random.random(3))
print(np.random.rand(3, 3))

[0.1255765  0.61653912 0.627763  ]
[[0.43030696 0.07451866 0.8395686 ]
 [0.82335762 0.04221095 0.45876884]
 [0.10447972 0.24807051 0.54183393]]


## Операції над масивами

In [14]:
a = np.arange(4)
b = np.arange(4, 8)

print(a + b)  # array([ 4,  6,  8, 10])
print(a - b)  # array([-4, -4, -4, -4])
print(a * b)  # array([ 0,  5, 12, 21])


[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]


In [15]:
np.sin(b)
np.sqrt(b)
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [18]:
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3)) * 5
print(A * B)


[[ 0.  5. 10.]
 [15. 20. 25.]
 [30. 35. 40.]]


In [22]:
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3))
print(np.dot(A, B))
print(A @ B)

[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [21]:
a = np.arange(4)
a+=1
print(a)

a -= 1
print(a)

[1 2 3 4]
[0 1 2 3]


# Ufunc — універсальні функції NumPy
| Функція          | Опис                                                                  |
|------------------|-----------------------------------------------------------------------|
| `np.sqrt()`      | Обчислює **квадратний корінь** з кожного елемента.                   |
| `np.log()`       | Обчислює **натуральний логарифм** кожного елемента.                 |
| `np.sin()`       | Обчислює **синус** кожного елемента (в радіанах).                   |
| `np.cos()`       | Обчислює **косинус** кожного елемента.                              |
| `np.exp()`       | Обчислює **експоненту** (e^x) для кожного елемента.                 |
| `np.abs()`       | Обчислює **модуль (абсолютне значення)** кожного елемента.          |
| `np.floor()`     | Округлює кожен елемент **вниз** до найближчого цілого.              |
| `np.ceil()`      | Округлює кожен елемент **вгору** до найближчого цілого.             |
| `np.round()`     | Округлює кожен елемент до найближчого цілого.

In [24]:
a = np.arange(1, 5)
print(np.sqrt(a))  # корінь
print(np.log(a))   # логарифм
print(np.sin(a))   # синус


[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


| Функція        | Опис                                                                 |
|----------------|----------------------------------------------------------------------|
| `np.sum()`     | Повертає **суму всіх елементів** у масиві.                          |
| `np.min()`     | Повертає **найменше значення** серед елементів.                     |
| `np.max()`     | Повертає **найбільше значення** серед елементів.                    |
| `np.mean()`    | Обчислює **середнє арифметичне** значення масиву.                   |
| `np.std()`     | Обчислює **стандартне відхилення** елементів.                       |
| `np.var()`     | Обчислює **дисперсію** масиву (середнє квадратичне відхилення).     |
| `np.prod()`    | Повертає **добуток всіх елементів** масиву.                         |

In [26]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())


15.0
0.3
5.7
3.0
2.0079840636817816


## Indexing and iterating

In [4]:
a = np.arange(10, 16)
print(a[4])
print(a[-1])
print(a[-6])
print(a[[1, 3, 4]])


14
15
10
[11 13 14]


In [5]:
A = np.arange(10, 19).reshape((3, 3))
print(A[1, 2])

print(A[0, :])
print(A[:, 0])



15
[10 11 12]
[10 13 16]


In [6]:
print(a[1:5])
print(a[1:5:2])
print(a[::2])
print(a[:5:2])


[11 12 13 14]
[11 13]
[10 12 14]
[10 12 14]


In [8]:
print(A[0:2, 0:2])

print(A[[0, 2], 0:2])


[[10 11]
 [13 14]]
[[10 11]
 [16 17]]


In [9]:
a = np.array([10, 11, 12, 13, 14, 15])

for i in a:
    print(i)

10
11
12
13
14
15


## Conditions and boolean indexing

In [10]:
A = np.random.random((4, 4))
print(A)

[[0.8536988  0.74750043 0.89917012 0.66545954]
 [0.14617788 0.81452564 0.95109349 0.06757264]
 [0.85489232 0.87979132 0.08153446 0.48068425]
 [0.99244883 0.88964482 0.98176804 0.28259341]]


In [11]:
A = np.random.random((4, 4))
print("Matrix A:")
print(A)

# Отримаємо булевий масив: True — де елемент < 0.5
mask = A < 0.5
print("\nA < 0.5:")
print(mask)

Matrix A:
[[0.40288076 0.11945007 0.1111165  0.17476368]
 [0.35685886 0.26443846 0.42765411 0.55768545]
 [0.36504821 0.77103729 0.19758015 0.33841641]
 [0.48708306 0.05923608 0.4796124  0.24174431]]

A < 0.5:
[[ True  True  True  True]
 [ True  True  True False]
 [ True False  True  True]
 [ True  True  True  True]]


In [12]:
print("\nElements in A less than 0.5:")
print(A[A < 0.5])


Elements in A less than 0.5:
[0.40288076 0.11945007 0.1111165  0.17476368 0.35685886 0.26443846
 0.42765411 0.36504821 0.19758015 0.33841641 0.48708306 0.05923608
 0.4796124  0.24174431]


# Arrays reshape

In [1]:
a = np.random.random(12)
print("Оригінальний масив:")
print(a)

A = a.reshape(3, 4)
print("\nПісля перетворення на матрицю 3x4:")
print(A)

Оригінальний масив:
[0.74762559 0.35845619 0.10794486 0.71367492 0.151479   0.63747156
 0.44406008 0.38575697 0.9141618  0.50723197 0.98808932 0.60106271]

Після перетворення на матрицю 3x4:
[[0.74762559 0.35845619 0.10794486 0.71367492]
 [0.151479   0.63747156 0.44406008 0.38575697]
 [0.9141618  0.50723197 0.98808932 0.60106271]]


In [2]:
a = np.random.random(12)
a.shape = (3, 4)
print("Зміна форми без створення нового об'єкта:")
print(a)

Зміна форми без створення нового об'єкта:
[[0.4392854  0.82519573 0.28872302 0.09480376]
 [0.82670303 0.77903053 0.31328391 0.58524549]
 [0.66249816 0.04975003 0.04982369 0.69509072]]


In [3]:
A = np.random.random((3, 4))
print("Початкова матриця:")
print(A)

a = A.ravel()
print("\nПеретворення матриці в 1D масив:")
print(a)

Початкова матриця:
[[0.38981092 0.20219343 0.03829457 0.55058778]
 [0.90508013 0.6891343  0.90998629 0.01752347]
 [0.18517472 0.77097601 0.56123698 0.3685909 ]]

Перетворення матриці в 1D масив:
[0.38981092 0.20219343 0.03829457 0.55058778 0.90508013 0.6891343
 0.90998629 0.01752347 0.18517472 0.77097601 0.56123698 0.3685909 ]


In [4]:
A = np.random.random((3, 4))
A.shape = (A.size,)
print("Зміна форми матриці на 1D масив через size:")
print(A)

Зміна форми матриці на 1D масив через size:
[0.73197027 0.03814548 0.96340563 0.94774814 0.05205259 0.26126829
 0.8004033  0.26242927 0.82552224 0.49140101 0.94098901 0.12771502]


In [5]:
A = np.random.random((3, 4))
print("Початкова матриця:")
print(A)

T = A.transpose()
print("\nТранспонована матриця:")
print(T)

Початкова матриця:
[[0.53771178 0.75184749 0.33787512 0.18240863]
 [0.27612238 0.98220473 0.99131185 0.71768519]
 [0.05313818 0.91399927 0.83336053 0.6010416 ]]

Транспонована матриця:
[[0.53771178 0.27612238 0.05313818]
 [0.75184749 0.98220473 0.91399927]
 [0.33787512 0.99131185 0.83336053]
 [0.18240863 0.71768519 0.6010416 ]]


# Array manipulation

In [6]:
A = np.ones((3, 3))
B = np.zeros((3, 3))

print("Вертикальне об'єднання (vstack):")
print(np.vstack((A, B)))

print("\nГоризонтальне об'єднання (hstack):")
print(np.hstack((A, B)))

Вертикальне об'єднання (vstack):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Горизонтальне об'єднання (hstack):
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [8]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

print("Об'єднання як стовпці:")
print(np.column_stack((a, b, c)))

print("\nОб'єднання як рядки:")
print(np.vstack((a, b, c)))

Об'єднання як стовпці:
[[0 3 6]
 [1 4 7]
 [2 5 8]]

Об'єднання як рядки:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
A = np.arange(16).reshape((4, 4))
print("Матриця A:")
print(A)

# Горизонтальне розбиття (2 матриці по 2 стовпці)
[B, C] = np.hsplit(A, 2)
print("\nГоризонтальне розбиття (hsplit):")
print("B:\n", B)
print("C:\n", C)

# Вертикальне розбиття (2 матриці по 2 рядки)
[B, C] = np.vsplit(A, 2)
print("\nВертикальне розбиття (vsplit):")
print("B:\n", B)
print("C:\n", C)

Матриця A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Горизонтальне розбиття (hsplit):
B:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
C:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Вертикальне розбиття (vsplit):
B:
 [[0 1 2 3]
 [4 5 6 7]]
C:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [11]:
A = np.arange(16).reshape((4, 4))
print("Матриця A:")
print(A)

# Розбиваємо на три частини по стовпцях
[A1, A2, A3] = np.split(A, [1, 3], axis=1)

print("A1:\n", A1)
print("A2:\n", A2)
print("A3:\n", A3)

Матриця A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
A1:
 [[ 0]
 [ 4]
 [ 8]
 [12]]
A2:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
A3:
 [[ 3]
 [ 7]
 [11]
 [15]]


In [12]:
[A1, A2, A3] = np.split(A, [1, 3], axis=0)

print("A1:\n", A1)
print("A2:\n", A2)
print("A3:\n", A3)

A1:
 [[0 1 2 3]]
A2:
 [[ 4  5  6  7]
 [ 8  9 10 11]]
A3:
 [[12 13 14 15]]
