In [2]:
import numpy as np

ndarray: Серце бібліотеки NumPy

ndarray — це багатовимірний однорідний масив (всі елементи одного типу).

Тип даних кожного елемента задається об'єктом dtype.

Ключові атрибути масиву:

| Атрибут     | Опис                                                             |
|-------------|------------------------------------------------------------------|
| `dtype`     | Тип елементів у масиві                                          |
| `ndim`      | Кількість вимірів (осей)                                        |
| `shape`     | Форма (розміри по кожній осі), наприклад `(3, 4)`               |
| `size`      | Загальна кількість елементів у масиві                           |
| `itemsize`  | Розмір одного елемента в байтах                                 |
| `data`      | Вказівник на блок пам’яті з фактичними елементами масиву       |



In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))       # <class 'numpy.ndarray'>
print(a.dtype)       # int32 (або int64)
print(a.ndim)        # 1
print(a.shape)       # (3,)
print(a.size)        # 3
print(a.itemsize)    # 4 або 8 (залежить від платформи)


<class 'numpy.ndarray'>
int64
1
(3,)
3
8


# Створення масиву

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([(1, 2), [3, 4], (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

## типи даних

| Data Type   | Description                                                                                           |
|:------------|:------------------------------------------------------------------------------------------------------|
| `bool_`     | Булевий тип (true або false), збережений у вигляді байта                                               |
| `int_`      | Знаковий тип цілого числа (як у C long та Python int; зазвичай int64 або int32 залежно від платформи) |
| `intc`      | Знаковий тип цілого числа, ідентичний до C int (зазвичай int32 або int64)                             |
| `intptr`    | Ціле число для індексування (як size_t у C; зазвичай int32 або int64)                                |
| `int8`      | Псевдонім знакового цілого типу з 8 бітами (−128 до 127)                                             |
| `int16`     | Псевдонім знакового цілого типу з 16 бітами (−32768 до 32767)                                        |
| `int32`     | Псевдонім знакового цілого типу з 32 бітами (−2147483648 до 2147483647)                              |
| `int64`     | Псевдонім знакового цілого типу з 64 бітами (−9223372036854775808 до 9223372036854775807)            |
| `uint8`     | Псевдонім беззнакового цілого типу з 8 бітами (0 до 255)                                             |
| `uint16`    | Псевдонім беззнакового цілого типу з 16 бітами (0 до 65535)                                          |
| `uint32`    | Псевдонім беззнакового цілого типу з 32 бітами (0 до 4294967295)                                     |
| `uint64`    | Псевдонім беззнакового цілого типу з 64 бітами (0 до 18446744073709551615)                          |
| `float_`    | Скорочений запис для float64                                                                          |
| `float16`   | Число з плаваючою комою напівточності: біт знаку, 5-бітний експонент, 10-бітова мантиса               |
| `float32`   | Число з плаваючою комою одиничної точності: біт знаку, 8-бітний експонент, 23-бітова мантиса           |
| `float64`   | Число з плаваючою комою подвійної точності: біт знаку, 11-бітний експонент, 52-бітова мантиса          |
| `complex_`  | Скорочений запис для complex128                                                                       |
| `complex64` | Комплексне число, представлене двома 32-бітними числами з плаваючою комою (дійсна та уявна частини)   |
| `complex128`| Комплексне число, представлене двома 64-бітними числами з плаваючою комою (дійсна та уявна частини)   |


In [8]:
b = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(b.dtype)  # float32


float32


## Створення масивів іншими способами

| Функція                         | Пояснення                                                                 |
|-------------------------------|---------------------------------------------------------------------------|
| `np.zeros(shape)`             | Створює масив заданої форми, заповнений нулями                            |
| `np.ones(shape)`              | Створює масив заданої форми, заповнений одиницями                         |
| `np.arange(stop)`             | Створює послідовність від 0 до `stop` (не включно)                         |
| `np.arange(start, stop)`      | Послідовність від `start` до `stop` (не включно)                          |
| `np.arange(start, stop, step)`| Послідовність з кроком `step`                                             |
| `np.linspace(start, stop, num)` | Повертає `num` значень між `start` і `stop` з рівним інтервалом          |
| `np.random.random(size)`      | Масив заданого розміру з випадковими числами від 0 до 1                   |
| `arr.reshape(shape)`          | Перетворює одномірний масив у масив заданої форми                         |


In [9]:
print(np.zeros((3, 3)))
print(np.ones((3, 3)) )


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.arange(0, 10)  )
print(np.arange(4, 10))
print(np.arange(0, 12, 3))
print(np.arange(0, 6, 0.6))
print(np.arange(0, 12).reshape(3, 4))


[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[0 3 6 9]
[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print(np.linspace(0, 10, 5))


[ 0.   2.5  5.   7.5 10. ]


In [12]:
print(np.random.random(3))
print(np.random.rand(3, 3))

[0.1255765  0.61653912 0.627763  ]
[[0.43030696 0.07451866 0.8395686 ]
 [0.82335762 0.04221095 0.45876884]
 [0.10447972 0.24807051 0.54183393]]


## Операції над масивами

In [14]:
a = np.arange(4)
b = np.arange(4, 8)

print(a + b)  # array([ 4,  6,  8, 10])
print(a - b)  # array([-4, -4, -4, -4])
print(a * b)  # array([ 0,  5, 12, 21])


[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]


In [15]:
np.sin(b)
np.sqrt(b)
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [18]:
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3)) * 5
print(A * B)


[[ 0.  5. 10.]
 [15. 20. 25.]
 [30. 35. 40.]]


In [22]:
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3))
print(np.dot(A, B))
print(A @ B)

[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [21]:
a = np.arange(4)
a+=1
print(a)

a -= 1
print(a)

[1 2 3 4]
[0 1 2 3]


# Ufunc — універсальні функції NumPy
| Функція          | Опис                                                                  |
|------------------|-----------------------------------------------------------------------|
| `np.sqrt()`      | Обчислює **квадратний корінь** з кожного елемента.                   |
| `np.log()`       | Обчислює **натуральний логарифм** кожного елемента.                 |
| `np.sin()`       | Обчислює **синус** кожного елемента (в радіанах).                   |
| `np.cos()`       | Обчислює **косинус** кожного елемента.                              |
| `np.exp()`       | Обчислює **експоненту** (e^x) для кожного елемента.                 |
| `np.abs()`       | Обчислює **модуль (абсолютне значення)** кожного елемента.          |
| `np.floor()`     | Округлює кожен елемент **вниз** до найближчого цілого.              |
| `np.ceil()`      | Округлює кожен елемент **вгору** до найближчого цілого.             |
| `np.round()`     | Округлює кожен елемент до найближчого цілого.

In [24]:
a = np.arange(1, 5)
print(np.sqrt(a))  # корінь
print(np.log(a))   # логарифм
print(np.sin(a))   # синус


[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


| Функція        | Опис                                                                 |
|----------------|----------------------------------------------------------------------|
| `np.sum()`     | Повертає **суму всіх елементів** у масиві.                          |
| `np.min()`     | Повертає **найменше значення** серед елементів.                     |
| `np.max()`     | Повертає **найбільше значення** серед елементів.                    |
| `np.mean()`    | Обчислює **середнє арифметичне** значення масиву.                   |
| `np.std()`     | Обчислює **стандартне відхилення** елементів.                       |
| `np.var()`     | Обчислює **дисперсію** масиву (середнє квадратичне відхилення).     |
| `np.prod()`    | Повертає **добуток всіх елементів** масиву.                         |

In [26]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())


15.0
0.3
5.7
3.0
2.0079840636817816
